# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 10:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=320, null=True)),
                ('last_name', models.CharField(blank=True, max_length=320, null=True)),
                ('pg_name', models.CharField(blank=True, max_length=320, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('email', models.EmailField(blank=True, max_length=520, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('height_field', models.IntegerField(blank=True, null=True)),
                ('width_field', models.IntegerField(blank=True, null=True)),
                ('adhar_img', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field1', models.IntegerField(blank=True, null=True)),
                ('width_field1', models.IntegerField(blank=True, null=True)),
                ('pan_img', models.ImageField(blank=True, height_field='height_field1', null=True, upload_to='', width_field='width_field1')),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
                ('occupatin', models.CharField(blank=True, max_length=320, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('food_required', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100, null=True)),
                ('food_amt', models.IntegerField(blank=True, null=True)),
                ('advance_amt', models.IntegerField(blank=True, null=True)),
                ('joining_date', models.DateField(null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100, null=True)),
                ('vacate_date', models.DateField(null=True)),
                ('log_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
