# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenantmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdetails',
            name='vacate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
